[[manager.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"


[[manager.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm
''', "yank" ]

[[manager.prepend_keymap]]
on   = "<Right>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"


[[manager.prepend_keymap]]
on   = [ "i" ]
run = "plugin easyjump"
desc = "easyjump"


[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch --args=zip"
desc = "Compress with ouch"


[[manager.prepend_keymap]]
on   = "<C-d>"
run  = "plugin diff"
desc = "Diff the selected with the hovered file"


[[manager.prepend_keymap]]
on   = "f"
run  = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = ["t", "u"]
run = "tab_create --current"
desc = "Create a new tab using the current path"

[[manager.prepend_keymap]]
on = ["t", "n"]
run = "tab_switch -1 --relative"
desc = "Switch to the previous tab"

[[manager.prepend_keymap]]
on = ["t", "i"]
run = "tab_switch 1 --relative"
desc = "Switch to the next tab"

[[manager.prepend_keymap]]
on = ["t", "q"]
run = "close"
desc = "Close the current tab, or quit if it is last tab"

[[manager.prepend_keymap]]
on  = "<C-x>"
run = 'shell -- dragon-drop -x -i -T "$1"'
desc = "Drag and drop via"


[[manager.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]
desc = "Copy selected files to system clipboard"

