[manager]
show_hidden = true


[opener]
pdfreader = [
  {  run = 'zathura "$@"', block = true  }
]

docx = [
    { run = 'libreoffice "$@"', block = true }
]

edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
image = [
  { run = 'imv "$@"', desc = "Image" }
]
extract = [
	{ run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]


[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
]
prepend_rules = [
	# Multiple openers for a single rule
	{ name = "*.html", use = [ "browser", "text" ] },
  { name = "*.json", use = ["edit"]   },
  { name = "*.lua", use = ["edit"]   },
  { name = "*.db", use = ["edit"]   },
  { name = "*.c", use = ["edit"]   },
  { name = "*.png",  use = [ "image" ] },
  { name = "*.jpg",  use = [ "image" ] },
  { name = "*.webp", use = [ "image" ] },
  { name = "*.svg", use = [ "image" ] },
  { name = "*.ico", use = [ "image" ] },
  { name = "*.zip",  use = ["extract"] },
  { name = "*.tar",  use = ["extract"]  },
  { name = "*.rar",  use = ["extract"]  },
  { name = "*.7z",   use = ["extract"]  },
  { name = "*.xz",   use = ["extract"]  },
  { name = "*.pdf",   use = ["pdfreader"]  },
  { name = "*.py",      use = ["edit"] },
  { name = "*.docx", use = ["docx"] }
]
append_rules = [
  { name = "*",      use = ["open"] },
]


[plugin]
prepend_previewers = [
  # mardown previewer
  { name = "*.md", run = "glow" },
  # epub previewer
  { name = "*.epub", run = "epub" },
	# archive previewer
	{ mime = "application/zip",             run = "ouch" },
	{ mime = "application/gzip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip",          run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
	{ mime = "application/pdf",             run = "ouch" },
  { mime = "{image,audio,video}/*",       run = "mediainfo"},
]

prepend_preloaders= [
  { name = "*.epub", run = "epub" },
]

