[manager]
show_hidden = true


[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
image = [
  { run = 'imv "$@"', desc = "Image" }
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
  #{ mime = "application/json", use = "text" },

	# Multiple openers for a single rule
	{ name = "*.html", use = [ "browser", "text" ] },
  { name = "*.png", use = [ "image" ] },
  { name = "*.jpg", use = [ "image" ] },
  { name = "*.webp", use = [ "image" ] },

  { name = "*", use = ["open"] }

]


[plugin]
prepend_previewers = [
  # mardown previewer
  { name = "*.md", exec = "glow" },
	# Archive previewer
	{ mime = "application/zip",             run = "ouch" },
	{ mime = "application/gzip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip",          run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
	{ mime = "application/pdf",             run = "ouch" },
]
